# Site settings
title: from prior to posterior 
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Paulo Roberto de Oliveira Castro Blog"
baseurl: ""
url: "http://yourdomain.com"
github_username:  prcastro

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
